# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
    groups:
      # Group updates together, so that they are all applied in a single PR.
      # Grouped updates are currently in beta and is subject to change.
      # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      k8s-go-deps:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
        exclude-patterns:
          - "sigs.k8s.io/karpenter"
      go-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
    ignore:
      - dependency-name: "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice"
        versions:
          - ">=v8.0.0" # AKS Machine API is externally in preview. Need to preserve beta versions of the module.
  - package-ecosystem: docker
    directories:
      - /.devcontainer/**/*
    groups:
      devcontainer-deps:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
  - package-ecosystem: docker
    directory: /hack/go-helper-image
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
  - package-ecosystem: github-actions
    directory: / # covers .github/workflows
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
    groups:
      # Group updates together, so that they are all applied in a single PR.
      # Grouped updates are currently in beta and is subject to change.
      # xref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      actions-deps:
        patterns:
          - "*"
  # Everything under this line is currently auto-generated by hack/github/dependabot.sh
  # This needs to be generated since composite actions are currently not supported for auto-updates
  # through dependabot without explicitly setting their directory: https://github.com/dependabot/dependabot-core/issues/6704
  # If you need to make a change to this file, ensure that you make a change to hack/github/dependabot.sh first
  # That script assumes that the number of elements above this line is static and bases the append operation on it
  - package-ecosystem: github-actions
    directory: .github/actions/commit-status/end
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/commit-status/start
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/download-artifact
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/e2e/cleanup
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/e2e/create-acr
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/e2e/create-cluster
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/e2e/dump-logs
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/e2e/install-helm
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/e2e/install-karpenter
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: .github/actions/install-deps
    schedule:
      interval: weekly
    labels:
      - area/dependency
    groups:
      action-deps:
        patterns:
          - '*'
