apiVersion: v2
name: karpenter-crd
description: A Helm chart for AKS Karpenter provider Custom Resource Definitions (CRDs)
type: application
version: 0.1.0
appVersion: 0.1.0
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
home: https://github.com/Azure/karpenter/
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
sources:
  - https://github.com/Azure/karpenter/
